apiVersion: v1
kind: Service
metadata:
  name: flapp
  labels:
    run: flapp
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    run: flapp
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: flapp
  name: flapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flapp
  template:
    metadata:
      labels:
        run: flapp
    spec:
      containers:
      - args:
        - /app/app.py
        command:
        - python
        image: sharifabdulcoder/flapp:v2
        name: flapp
        # livenessProbe:
        #   httpGet:
        #     path: /healthy
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
        #   periodSeconds: 10
        #   failureThreshold: 3
